
version: '3.3'
services:

  db:
    image: mysql:latest
    volumes:
      - db5:/var/lib/mysql

    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_USER=user
    ports:
      - "3307:3306"
   # restart: always



  customerservice:                        #it is just a name, which will be used only in this file.
    image: customer-service               #name of the image after dockerfile executes
    container_name: customer-service-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    #restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_PROFILES_ACTIVE: MySQLdocker

volumes: #Dichiarazione del volume, obbligatoria
  db5: