
version: '3.3'
services:

  my-sql-db:
    image: mysql:latest
   # volumes:
   #   - db5:/var/lib/mysql

    #container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_USER=user
      - MYSQL_DATABASE=spring-app

    ports:
      - "3306:3306"



  customerservice:
    image: customer-service
    #container_name: customer-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - my-sql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-sql-db:3306/spring-app?createDatabaseIfNotExist=true
#volumes: #Dichiarazione del volume, obbligatoria
 # db5: