---
server:
  port: 8080
  servlet:
    context-path: /spring-app
spring:
  application:
    name: spring-app
  profiles:
    active: none

---
spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: CET
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: h2db

---
spring:


  jpa:
    open-in-view: true #per levare warnig OpenSessionInView
    properties:
      hibernate:
        jdbc:
          time_zone: CET
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    generate-ddl: true
    show-sql: true
    url: jdbc:mysql://localhost:3306/spring-app?createDatabaseIfNotExist=true
    username: operations
    password: operations
    driverClassName: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: MySQL



---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-app?createDatabaseIfNotExist=true
    username: operations
    password: operations
  jpa:
    open-in-view: true #per levare warnig OpenSessionInView
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  config:
    activate:
      on-profile: MySQL2


---

spring:
  jpa:
    open-in-view: false #per levare warnig OpenSessionInView
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: CET
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://my-sql-db:3306/spring-app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: user
    password: user
  config:
    activate:
      on-profile: MySQLdocker
