---
server:
  port: 8080
  servlet:
    context-path: /spring-app
spring:
  application:
    name: spring-app
  profiles:
    active: MySQL2

---
spring:
  jpa:
    open-in-view: false #per levare warnig OpenSessionInView
    properties:
      hibernate:
        jdbc:
          time_zone: CET
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: h2db

---
spring:

  #autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  jpa:
    open-in-view: false #per levare warnig OpenSessionInView
    properties:
      hibernate:
        jdbc:
          time_zone: CET
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    generate-ddl: true
    show-sql: true
    url: jdbc:mysql://localhost:3306/spring-app?createDatabaseIfNotExist=true
    username: operations
    password: operations
    driverClassName: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: MySQL

---

spring:
  jpa:
    open-in-view: false #per levare warnig OpenSessionInView
    properties:
      hibernate:
        jdbc:
          time_zone: CET
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://mysql-db2:3306/customer?createDatabaseIfNotExist=true
    username: operations
    password: operations
  config:
    activate:
      on-profile: test1

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-app?createDatabaseIfNotExist=true
    username: operations
    password: operations
  jpa:
    open-in-view: false #per levare warnig OpenSessionInView
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  config:
    activate:
      on-profile: MySQL2
