name: e2e-tests

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of SonarQube analysis
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: docker-compose
        run: docker-compose up -d
      - name: Sleep for 30 seconds
        run: sleep 60s
        shell: bash
      - name: check-compose
        run: docker ps -a
      - name: check-compose
        run:  docker logs my-spring-project_customerservice_1
      - name: End-to-end tests
        run: xvfb-run mvn verify -P e2e-tests #to run only e2e
      - name: check-compose
        run: docker ps -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
